#logging.config: "classpath:logback.xml"
#logging.level:
#  root: INFO
#  uk.co.telegraph.travel: INFO

server:
  port: 8090
  servlet.contextPath: "/sales"

management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      base-path: "/" # actuator endpoints modified from e.g. /actuator/health to /health"
      exposure:
        include: "health, info, metrics"
