version: '2.1'
services:
  web:
    build:
      context: frontend
  
  api:
    build:
      context: backend

  chromedriver:
    image: blueimp/chromedriver
    environment:
      - VNC_ENABLED=true
      - EXPOSE_X11=true
    ## uncomment this for VNC enabled inspection
    # ports:    
    #   - 3002:5900

  automation:
    build:
      context: automation
    depends_on:
      - chromedriver
      - web
      - api
    environment:
      - CUSTOM_VAR=${VALUE}
      - WAIT_FOR_HOSTS=chromedriver:4444 chromedriver:6060 web:3001 api:3000      
    volumes:
      - ./automation:/app
