export const STATE_TYPE = {
  simple: 'inmemory-state',
  persisted: 'persisted-state'
};

export const ACTIONS_TYPES = {
  LOGIN_ACTION_REQUEST: 'LOGIN_ACTION_REQUEST',
  LOGIN_ACTION_SUCCESS: 'LOGIN_ACTION_SUCCESS',
  LOGIN_ACTION_ERROR: 'LOGIN_ACTION_ERROR',
  LOGOUT_ACTION_REQUEST: 'LOGOUT_ACTION_REQUEST'
};
